### ISSUE TITLE
Discussão dos resultados dos contatos realizados com os locais pesquisados.

### ISSUE THREAD

**Issue by victor4pinheiro** [Avengers042/projeto-integrado#7]
Coloquem aqui os resultados dos contatos. A issue #4 foi finalizada justamente por ter atendido o critério de realizar contato.
Os resultados serão colocados por eu e pelo @Axl886 , mas a discussão será realizada entre todos, incluindo @Samuka0909 e @Matheus-Mapg .
O tempo é indefinido, pois o prazo de contato é variável, mas é importante enfatizar que, em caso de longa demora, procuraremos novos locais.
Já a pesquisa de novos locais para possível contato ficará em aberto, ou seja, continuem procurando novos locais e realizem o contato, e coloquem quando fizeram o contato e qual o resultado (um comentário por contato para não poluir demais.)

**Comment by victor4pinheiro** [comment]
Contato: C yong
Dia do primeiro contato: 02/09/2022
Resultado: No aguardo.

**Comment by victor4pinheiro** [comment]
Contato: Anabya Bolsas, Calçados
Dia do primeiro contato: 02/09/2022
Resultado: No aguardo.

**Comment by victor4pinheiro** [comment]
Contato: Data Especial Presentes
Dia do primeiro contato: 02/09/2022
Resultado: No aguardo.

**Comment by victor4pinheiro** [comment]
Contato: Estrela Esporte Gama Shopping
Dia do primeiro contato: 02/09/2022
Resultado: No aguardo.

**Comment by Axl886** [comment]
Contato: PlakarSports
Dia do primeiro contato: 31/08/2022
Resultado: No aguardo.

**Comment by Axl886** [comment]
Contato: Gama Tech Gama Shopping
Dia do primeiro contato: 31/08/2022
Resultado: No aguardo.

**Comment by Axl886** [comment]
Contato: Japao da Construção
Dia do primeiro contato: 31/08/2022
Resultado: No aguardo.

**Comment by Axl886** [comment]
Contato: UTI dos Notebooks
Dia do primeiro contato: 31/08/2022
Resultado: No aguardo.

**Comment by victor4pinheiro** [comment]
Projeto será refeito pela falta de stakeholders.
